[2023-08-04T15:05:12.762+0000] {processor.py:157} INFO - Started process (PID=30) to work on /opt/airflow/dags/template/tomtom_dag.py
[2023-08-04T15:05:12.771+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/tomtom_dag.py for tasks to queue
[2023-08-04T15:05:12.776+0000] {logging_mixin.py:150} INFO - [2023-08-04T15:05:12.776+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/tomtom_dag.py
[2023-08-04T15:05:12.869+0000] {logging_mixin.py:150} INFO - [2023-08-04T15:05:12.867+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/tomtom_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/tomtom_dag.py", line 30, in <module>
    '--date {{ ds }} --connection %s' % Variable.get("data_dev_connection")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable data_dev_connection does not exist'
[2023-08-04T15:05:12.870+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/tomtom_dag.py
[2023-08-04T15:05:12.919+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/tomtom_dag.py took 0.174 seconds
[2023-08-04T15:05:43.375+0000] {processor.py:157} INFO - Started process (PID=60) to work on /opt/airflow/dags/template/tomtom_dag.py
[2023-08-04T15:05:43.377+0000] {processor.py:826} INFO - Processing file /opt/airflow/dags/template/tomtom_dag.py for tasks to queue
[2023-08-04T15:05:43.379+0000] {logging_mixin.py:150} INFO - [2023-08-04T15:05:43.378+0000] {dagbag.py:541} INFO - Filling up the DagBag from /opt/airflow/dags/template/tomtom_dag.py
[2023-08-04T15:05:43.418+0000] {logging_mixin.py:150} INFO - [2023-08-04T15:05:43.416+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/template/tomtom_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/template/tomtom_dag.py", line 30, in <module>
    '--date {{ ds }} --connection %s' % Variable.get("data_dev_connection")
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/variable.py", line 142, in get
    raise KeyError(f"Variable {key} does not exist")
KeyError: 'Variable data_dev_connection does not exist'
[2023-08-04T15:05:43.419+0000] {processor.py:838} WARNING - No viable dags retrieved from /opt/airflow/dags/template/tomtom_dag.py
[2023-08-04T15:05:43.427+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/template/tomtom_dag.py took 0.056 seconds
